### ISSUE TITLE
Formatter may need more options

### ISSUE THREAD

**Issue by FFengIll** [tintinweb/vscode-interactive-graphviz#109] opened 2022-05-13 03:58 UTC
I see a new formatter comes into the extension (v0.3).
It is good, but mandatary now - adding some options to configure by users might be better.

> comment here: https://github.com/tintinweb/vscode-interactive-graphviz/commit/a6b963a7bd6689bd8f98fe3e8569898110016304#r73550516

**Comment by FFengIll** [comment] 2022-05-13 04:00
some candidate options
- auto-sort: bool
- auto-quote: bool

**Comment by FFengIll** [comment] 2022-05-13 04:04
original
<img width="277" alt="image" src="https://user-images.githubusercontent.com/7359555/168209025-dfbbe78c-8252-41f1-9b6c-23f803397f8f.png">
after format
<img width="321" alt="image" src="https://user-images.githubusercontent.com/7359555/168209101-b0b77879-13f5-4bbd-ab78-8fff99ca5da9.png">

**Comment by bigbug** [comment] 2022-06-19 14:42
The Quoting will be fixed with #111 
Sorting Issues could not be reproduced. Do you have an example? Or is this a feature request?

**Comment by bigbug** [comment] 2022-08-15 20:00
Closed due to inactivity

**Closed by bigbug** 2022-08-15 20:00 UTC
